kind: pipeline
name: julia-latest
steps:
- name: logisitic_regression
  image: julia:latest
  commands:
    - julia -e 'using Pkg; Pkg.activate("."); Pkg.test()'
  when:
    event:
      - pull_request
      - push
