kind: pipeline
name: julia-latest
steps:
- name: logisitic_regression
  image: julia:latest
  commands:
    - julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.test()'
  when:
    event:
      - pull_request
      - push
